try:
    # print(num)
    print(2/0)
except Exception as result:
    print(result)